name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  build-jvm-and-linux:
    runs-on: ubuntu-latest
    env:
      OS: linux
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - run: mvn clean package
      - name: tar-gz
        run: tar -czvf quarkus-app.tar.gz -C quarkus-app .
        working-directory: ./target/
      - name: Upload JVM Quarkus app
        id: upload-jvm-quarkus-app
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/quarkus-app.tar.gz
          asset_name: quarkus-app.tar.gz
          tag: ${{ github.ref }}
          overwrite: true
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          # GraalVM version, no pattern syntax available atm
          graalvm: '21.3.0'
          # Java version, optional, defaults to 'java8'. Available options are 'java8' and 'java11'.
          java: 'java11'
          # Architecture flag, optional, defaults to 'amd64'. Available options are 'amd64' and 'aarch64'. Later is available only for linux runners.
          arch: 'amd64'

      - name: Install native-image component
        run: |
          gu install native-image
      - name: Build native executable
        run: ./mvnw package -Dnative
      - name: Upload native executable
        id: upload-native-executable
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./target/quarked-ddns-runner
          asset_name: quarked-ddns-linux
          tag: ${{ github.ref }}
          overwrite: true